"""
This contains templates for trees when we want to set specific items 
"""

ADAPTERS = """<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp1 (http://www.altova.com)-->
<io:Adapter xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/ledm/iomgmt/2008/11/30 ../../schemas/IoMgmt.xsd" xmlns:n1="http://www.altova.com/samplexml/other-namespace" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:io="http://www.hp.com/schemas/imaging/con/ledm/iomgmt/2008/11/30" xmlns:map="http://www.hp.com/schemas/imaging/con/ledm/resourcemap/2009/01/27" xmlns:wifi="http://www.hp.com/schemas/imaging/con/wifi/2009/06/26" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<io:HardwareConfig>
		<dd:Power></dd:Power>
	</io:HardwareConfig>
</io:Adapter>
"""

CIMATION = """<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<cim:CIMation 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" 
	xmlns:cim="http://www.hp.com/schemas/imaging/con/ledm/CIMATION/2014/05/20" 
	xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/CIMATION/2014/05/20 CIMation.xsd">
	<cim:CALIBRATION-S2-CAL></cim:CALIBRATION-S2-CAL>
	<cim:SCAN-CALIBRATION-DOWNLOAD-1200></cim:SCAN-CALIBRATION-DOWNLOAD-1200>
	<cim:SCAN-CALIBRATION-DOWNLOAD-300-COLOR></cim:SCAN-CALIBRATION-DOWNLOAD-300-COLOR>
	<cim:SCAN-CALIBRATION-DOWNLOAD-300-MONO></cim:SCAN-CALIBRATION-DOWNLOAD-300-MONO>
	<cim:SCAN-CALIBRATION-DOWNLOAD-300-SCAN></cim:SCAN-CALIBRATION-DOWNLOAD-300-SCAN>
	<cim:SCAN-CALIBRATION-DOWNLOAD-600></cim:SCAN-CALIBRATION-DOWNLOAD-600>
	<cim:SCANNER-LAMP-GAIN-VALUE></cim:SCANNER-LAMP-GAIN-VALUE>
	<cim:SCANNER-REFERENCE-POSITION></cim:SCANNER-REFERENCE-POSITION>
	<cim:SCANNER-SCANLINE-STATISTICS></cim:SCANNER-SCANLINE-STATISTICS>
	<cim:SCANNER-SCANNER-EDUPLEX-CONFIG></cim:SCANNER-SCANNER-EDUPLEX-CONFIG>
	<cim:COPIER-ADF-TEST-MODE></cim:COPIER-ADF-TEST-MODE>
	<cim:COPIER-ADF-TEST-MODE-PAGE-COUNT></cim:COPIER-ADF-TEST-MODE-PAGE-COUNT>
	<cim:SCANNER-FACTORY-TEST-MODE></cim:SCANNER-FACTORY-TEST-MODE>
	<cim:SCANNER-SERVO-HISTORY-ENABLE></cim:SCANNER-SERVO-HISTORY-ENABLE>
	<cim:SCANNER-START-POSITION></cim:SCANNER-START-POSITION>
	<cim:ScannerType></cim:ScannerType>
    <cim:SCAN-IMAGE-PROCESSING></cim:SCAN-IMAGE-PROCESSING>.
	<cim:ScanPagesCount></cim:ScanPagesCount>
</cim:CIMation>
"""

CONSUMABLE_CONFIG_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<ccdyn:ConsumableConfigDyn 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" 
    xmlns:ccdyn="http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19" 
    xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19 ConsumableConfigDyn.xsd">
    <dd:Version>
        <dd:Revision></dd:Revision>
    </dd:Version>
    <ccdyn:ProductConsumableInfo>
        <dd:NumOfUserReplaceableConsumables></dd:NumOfUserReplaceableConsumables>
        <dd:NumOfNonUserReplaceableConsumables></dd:NumOfNonUserReplaceableConsumables>
        <ccdyn:AtVeryLowSettings>
            <ccdyn:ConsumableSetting>
                <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
                <dd:ConsumableStateAction></dd:ConsumableStateAction>
            </ccdyn:ConsumableSetting>
            <ccdyn:ConsumableSetting>
                <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
                <dd:ConsumableStateAction></dd:ConsumableStateAction>
            </ccdyn:ConsumableSetting>
        </ccdyn:AtVeryLowSettings>
        <dd:StoreUsageData></dd:StoreUsageData>
        <ccdyn:GenuineHPSuppliesOnly></ccdyn:GenuineHPSuppliesOnly>
    </ccdyn:ProductConsumableInfo>
    <ccdyn:ConsumableInfo>
        <dd:Capacity>
            <dd:MaxCapacity></dd:MaxCapacity>
            <dd:Unit></dd:Unit>
        </dd:Capacity>
        <dd:CartridgeModelInformation></dd:CartridgeModelInformation>
        <dd:CartridgeModelLife></dd:CartridgeModelLife>
        <dd:ConsumableFamilyName></dd:ConsumableFamilyName>
        <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
        <dd:ConsumableLifeState>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:MeasuredQuantityState></dd:MeasuredQuantityState>
            <dd:Brand></dd:Brand>
        </dd:ConsumableLifeState>
        <dd:ConsumableLowThreshold></dd:ConsumableLowThreshold>
        <dd:ConsumablePercentageLevelRemaining></dd:ConsumablePercentageLevelRemaining>
        <dd:ConsumableReplaceabilityType></dd:ConsumableReplaceabilityType>
        <dd:ConsumableSelectibilityNumber></dd:ConsumableSelectibilityNumber>
        <dd:ConsumableTypeEnum></dd:ConsumableTypeEnum>
        <dd:Manufacturer>
            <dd:Name></dd:Name>
            <dd:Date></dd:Date>
        </dd:Manufacturer>
        <dd:ProductNumber></dd:ProductNumber>
        <dd:SerialNumber></dd:SerialNumber>
        <dd:ConsumableManufacturingSignature></dd:ConsumableManufacturingSignature>
        <dd:ConsumableEstimatedPages>
            <dd:ValueInt></dd:ValueInt>
            <dd:PageYieldUnits></dd:PageYieldUnits>
        </dd:ConsumableEstimatedPages>
        <ccdyn:DataCollectionValid></ccdyn:DataCollectionValid>
    </ccdyn:ConsumableInfo>
    <ccdyn:ConsumableInfo>
        <dd:Capacity>
            <dd:MaxCapacity></dd:MaxCapacity>
            <dd:Unit></dd:Unit>
        </dd:Capacity>
        <dd:CartridgeModelInformation></dd:CartridgeModelInformation>
        <dd:CartridgeModelLife></dd:CartridgeModelLife>
        <dd:ConsumableFamilyName></dd:ConsumableFamilyName>
        <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
        <dd:ConsumableLifeState>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:MeasuredQuantityState></dd:MeasuredQuantityState>
            <dd:Brand></dd:Brand>
            <dd:ConsumableStateAction></dd:ConsumableStateAction>
        </dd:ConsumableLifeState>
        <dd:ConsumableLowThreshold></dd:ConsumableLowThreshold>
        <dd:ConsumablePercentageLevelRemaining></dd:ConsumablePercentageLevelRemaining>
        <dd:ConsumableReplaceabilityType></dd:ConsumableReplaceabilityType>
        <dd:ConsumableSelectibilityNumber></dd:ConsumableSelectibilityNumber>
        <dd:ConsumableTypeEnum></dd:ConsumableTypeEnum>
        <dd:Manufacturer>
            <dd:Name></dd:Name>
            <dd:Date></dd:Date>
        </dd:Manufacturer>
        <dd:ProductNumber></dd:ProductNumber>
        <dd:SerialNumber></dd:SerialNumber>
        <dd:ConsumableManufacturingSignature></dd:ConsumableManufacturingSignature>
        <dd:ConsumableEstimatedPages>
            <dd:ValueInt></dd:ValueInt>
            <dd:PageYieldUnits></dd:PageYieldUnits>
        </dd:ConsumableEstimatedPages>
        <ccdyn:DataCollectionValid></ccdyn:DataCollectionValid>
    </ccdyn:ConsumableInfo>
    <ccdyn:ConsumableInfo>
        <dd:Capacity>
            <dd:MaxCapacity></dd:MaxCapacity>
            <dd:Unit></dd:Unit>
        </dd:Capacity>
        <dd:CartridgeModelInformation></dd:CartridgeModelInformation>
        <dd:CartridgeModelLife></dd:CartridgeModelLife>
        <dd:ConsumableFamilyName></dd:ConsumableFamilyName>
        <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
        <dd:ConsumableLifeState>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:MeasuredQuantityState></dd:MeasuredQuantityState>
            <dd:Brand></dd:Brand>
        </dd:ConsumableLifeState>
        <dd:ConsumableStateAvailableActions>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:SupportedActions>
                <dd:ConsumableStateAction></dd:ConsumableStateAction>
            </dd:SupportedActions>
            <dd:DefaultAction></dd:DefaultAction>
        </dd:ConsumableStateAvailableActions>
        <dd:ConsumableLowThreshold></dd:ConsumableLowThreshold>
        <dd:ConsumablePercentageLevelRemaining></dd:ConsumablePercentageLevelRemaining>
        <dd:ConsumableReplaceabilityType></dd:ConsumableReplaceabilityType>
        <dd:ConsumableSelectibilityNumber></dd:ConsumableSelectibilityNumber>
        <dd:ConsumableTypeEnum></dd:ConsumableTypeEnum>
        <dd:Manufacturer>
            <dd:Name></dd:Name>
            <dd:Date></dd:Date>
        </dd:Manufacturer>
        <dd:ProductNumber></dd:ProductNumber>
        <dd:SerialNumber></dd:SerialNumber>
        <dd:ConsumableManufacturingSignature></dd:ConsumableManufacturingSignature>
        <dd:ConsumableEstimatedPages>
            <dd:ValueInt></dd:ValueInt>
            <dd:PageYieldUnits></dd:PageYieldUnits>
        </dd:ConsumableEstimatedPages>
        <ccdyn:DataCollectionValid></ccdyn:DataCollectionValid>
    </ccdyn:ConsumableInfo>
    <ccdyn:ConsumableInfo>
        <dd:Capacity>
            <dd:MaxCapacity></dd:MaxCapacity>
            <dd:Unit></dd:Unit>
        </dd:Capacity>
        <dd:CartridgeModelInformation></dd:CartridgeModelInformation>
        <dd:CartridgeModelLife></dd:CartridgeModelLife>
        <dd:ConsumableFamilyName></dd:ConsumableFamilyName>
        <dd:ConsumableLabelCode></dd:ConsumableLabelCode>
        <dd:ConsumableLifeState>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:MeasuredQuantityState></dd:MeasuredQuantityState>
            <dd:Brand></dd:Brand>
        </dd:ConsumableLifeState>
        <dd:ConsumableStateAvailableActions>
            <dd:ConsumableState></dd:ConsumableState>
            <dd:SupportedActions>
                <dd:ConsumableStateAction></dd:ConsumableStateAction>
            </dd:SupportedActions>
            <dd:DefaultAction></dd:DefaultAction>
        </dd:ConsumableStateAvailableActions>
        <dd:ConsumableLowThreshold></dd:ConsumableLowThreshold>
        <dd:ConsumablePercentageLevelRemaining></dd:ConsumablePercentageLevelRemaining>
        <dd:ConsumableReplaceabilityType></dd:ConsumableReplaceabilityType>
        <dd:ConsumableSelectibilityNumber></dd:ConsumableSelectibilityNumber>
        <dd:ConsumableTypeEnum></dd:ConsumableTypeEnum>
        <dd:Manufacturer>
            <dd:Name></dd:Name>
            <dd:Date></dd:Date>
        </dd:Manufacturer>
        <dd:ProductNumber></dd:ProductNumber>
        <dd:SerialNumber></dd:SerialNumber>
        <dd:ConsumableManufacturingSignature></dd:ConsumableManufacturingSignature>
        <dd:ConsumableEstimatedPages>
            <dd:ValueInt></dd:ValueInt>
            <dd:PageYieldUnits></dd:PageYieldUnits>
        </dd:ConsumableEstimatedPages>
        <ccdyn:DataCollectionValid></ccdyn:DataCollectionValid>
    </ccdyn:ConsumableInfo>
</ccdyn:ConsumableConfigDyn>
"""

COPY_CONFIG_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<cpcfgdyn:CopyConfigDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:cpcfgdyn="http://www.hp.com/schemas/imaging/con/ledm/cpcfgdyn/2008/05/05" xmlns:copy="http://www.hp.com/schemas/imaging/con/copy/2008/07/07" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/cpcfgdyn/2008/05/05 CopyConfigDyn.xsd http://www.hp.com/schemas/imaging/con/copy/2008/07/07 copy/copy.xsd">
  <dd:Version>
	<dd:Revision></dd:Revision>
  </dd:Version>
  <copy:DefaultLighterDarker></copy:DefaultLighterDarker>
  <copy:DefaultMediaSizeName></copy:DefaultMediaSizeName>
  <copy:DefaultMediaType></copy:DefaultMediaType>
  <copy:DefaultNumberOfCopies></copy:DefaultNumberOfCopies>
  <copy:DefaultOptimize></copy:DefaultOptimize>
  <copy:DefaultReduceEnlarge></copy:DefaultReduceEnlarge>
  <copy:DefaultReduceEnlargeCustom></copy:DefaultReduceEnlargeCustom>
  <copy:DefaultTraySelect></copy:DefaultTraySelect>
  <copy:DefaultCollation></copy:DefaultCollation>
  <copy:DefaultCopyDraft></copy:DefaultCopyDraft>
  <copy:DefaultMultiPage></copy:DefaultMultiPage>
  <dd:CopySides></dd:CopySides>
</cpcfgdyn:CopyConfigDyn>
"""

EICOMMAND_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<eicommand:EICommand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:eicommand="http://www.hp.com/schemas/imaging/con/ledm/eicommand/2009/02/07">
  <eicommand:decCommand></eicommand:decCommand>
</eicommand:EICommand>
"""
INTERNAL_PRINT_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<!--THIS DATA SUBJECT TO DISCLAIMER(S)INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<ipdyn:InternalPrintDyn xmlns:ipdyn="http://www.hp.com/schemas/imaging/con/ledm/internalprintdyn/2008/03/21" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/ledm/internalprintdyn/2008/03/21 ../schemas/InternalPrintDyn.xsd            http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ ../schemas/dd/DataDictionaryMasterLEDM.xsd">
<ipdyn:JobType/>
</ipdyn:InternalPrintDyn>
"""

MEDIA_DYN = """<?xml version="1.0" encoding="UTF-8" ?>
<!--  THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN.  -->
<mediadyn2:MediaDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:mediadyn="http://www.hp.com/schemas/imaging/con/ledm/mediadyn/2007/11/28" xmlns:mediadyn2="http://www.hp.com/schemas/imaging/con/ledm/mediadyn/2009/05/21" xmlns:ledm="http://www.hp.com/schemas/imaging/con/ledm/2007/09/21">
  <dd:MediaType />
  <dd:MediaSizeName />
</mediadyn2:MediaDyn>
"""

MEDIA_HANDLING_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<mhdyn:MediaHandlingDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:mhdyn="http://www.hp.com/schemas/imaging/con/ledm/mediahandlingdyn/2007/11/21" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ result/dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/mediahandlingdyn/2007/11/21 result/MediaHandlingDyn.xsd">
	<dd:Version>
		<dd:Revision></dd:Revision>
	</dd:Version>
	<mhdyn:MediaHandlingInfo>
		<dd:NumOfInputTrays></dd:NumOfInputTrays>
		<dd:NumOfOutputBins></dd:NumOfOutputBins>
		<dd:DefaultInputTray></dd:DefaultInputTray>
		<dd:DefaultOutputBin></dd:DefaultOutputBin>
		<dd:MediaOutTime></dd:MediaOutTime>
		<dd:MediaOutActionType></dd:MediaOutActionType>
	</mhdyn:MediaHandlingInfo>
	<mhdyn:InputTray>
		<dd:InputBin></dd:InputBin>
		<dd:MediaType></dd:MediaType>
		<dd:MediaSizeName></dd:MediaSizeName>
	</mhdyn:InputTray>
	<mhdyn:InputTray>
		<dd:InputBin></dd:InputBin>
		<dd:MediaType></dd:MediaType>
		<dd:MediaSizeName></dd:MediaSizeName>
	</mhdyn:InputTray>
	<mhdyn:InputTray>
		<dd:InputBin></dd:InputBin>
		<dd:MediaType></dd:MediaType>
		<dd:MediaSizeName></dd:MediaSizeName>
	</mhdyn:InputTray>
	<mhdyn:OutputBin>
		<dd:HPOutputBin></dd:HPOutputBin>
		<dd:MediaHandlingDeviceFunctionType></dd:MediaHandlingDeviceFunctionType>
	</mhdyn:OutputBin>
</mhdyn:MediaHandlingDyn>
"""

MANUFACTURING_CONFIG_DYN = """<?xml version="1.0" encoding="UTF-8" ?>
<!--   THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN.  
 --> 
 <mcdyn:ManufacturingConfigDyn 
     xmlns:mcdyn="http://www.hp.com/schemas/imaging/con/ledm/manufacturingconfig/2008/01/18" 
     xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/ledm/manufacturingconfig/2008/01/18 ../schemas/ManufacturingConfigDyn.xsd">
    
    <mcdyn:MfgSupport>
        <mcdyn:ID></mcdyn:ID>
        <mcdyn:ValueInt></mcdyn:ValueInt>
        <mcdyn:ValueString></mcdyn:ValueString>
    </mcdyn:MfgSupport>
    <mcdyn:MfgSupport>
        <mcdyn:ID></mcdyn:ID>
        <mcdyn:ValueInt></mcdyn:ValueInt>
        <mcdyn:ValueString></mcdyn:ValueString>
    </mcdyn:MfgSupport>
    <mcdyn:MfgSupport>
        <mcdyn:ID></mcdyn:ID>
        <mcdyn:ValueInt></mcdyn:ValueInt>
        <mcdyn:ValueString></mcdyn:ValueString>
    </mcdyn:MfgSupport>
    <mcdyn:ISAPower></mcdyn:ISAPower>
    <mcdyn:ControlPanelButtonPress></mcdyn:ControlPanelButtonPress>
    <mcdyn:ControlPanelVirtualButtonPress></mcdyn:ControlPanelVirtualButtonPress> 
    <mcdyn:ControlPanelScroll></mcdyn:ControlPanelScroll>
    <mcdyn:ServicePassword></mcdyn:ServicePassword>
    <mcdyn:ClearAllCounters></mcdyn:ClearAllCounters>
    <mcdyn:ErrorLogClear></mcdyn:ErrorLogClear>
    <mcdyn:ServiceErrorLogClear></mcdyn:ServiceErrorLogClear>
    <mcdyn:ClearNVRAM></mcdyn:ClearNVRAM>
    <mcdyn:Reset_SD_PDR_CPR></mcdyn:Reset_SD_PDR_CPR>
    <mcdyn:Reset_SD_CPR></mcdyn:Reset_SD_CPR>
    <mcdyn:ControlPanelDisplayContrast></mcdyn:ControlPanelDisplayContrast>
    <mcdyn:EnforceERPPowerRestrictions></mcdyn:EnforceERPPowerRestrictions>
    <mcdyn:EnforceERPLevel></mcdyn:EnforceERPLevel>
    <mcdyn:Calibrate></mcdyn:Calibrate>
    <mcdyn:DeviceConfigure>
          <mcdyn:CustomProductNumber></mcdyn:CustomProductNumber>
          <dd:MakeAndModel></dd:MakeAndModel>
          <dd:ProductNumber></dd:ProductNumber>
          <dd:SerialNumber></dd:SerialNumber>
          <dd:BoardInfo>
            <dd:BoardTypeEnum></dd:BoardTypeEnum>
            <dd:ModelNumber></dd:ModelNumber>
          </dd:BoardInfo>
          <mcdyn:InstallDate></mcdyn:InstallDate>
          <dd:ServiceID></dd:ServiceID> 
          <dd:HardwareAddress></dd:HardwareAddress>
          <mcdyn:SecureNvramItems>
              <mcdyn:NetworkSupport></mcdyn:NetworkSupport>
              <mcdyn:DCCNvramRestore></mcdyn:DCCNvramRestore>
              <mcdyn:ManufacturingModePreset></mcdyn:ManufacturingModePreset>
          </mcdyn:SecureNvramItems>
          <mcdyn:SystemShowEnergyLogo></mcdyn:SystemShowEnergyLogo>
          <mcdyn:RebootOnError></mcdyn:RebootOnError> 
          <mcdyn:PowerSaveTimeoutDefault></mcdyn:PowerSaveTimeoutDefault>
          <mcdyn:ShutDownDelayDefault></mcdyn:ShutDownDelayDefault>
          <mcdyn:WifiDirectDefault></mcdyn:WifiDirectDefault>
          <mcdyn:FormatterManagement>
              <mcdyn:NFCModuleDetected></mcdyn:NFCModuleDetected>
              <mcdyn:WirelessCardDetected></mcdyn:WirelessCardDetected>
              <mcdyn:FaxCardDetected></mcdyn:FaxCardDetected>
          </mcdyn:FormatterManagement>
          <mcdyn:NFCMemory>
              <mcdyn:MemoryCRC></mcdyn:MemoryCRC>
              <mcdyn:MemoryPresetProgram></mcdyn:MemoryPresetProgram>
          </mcdyn:NFCMemory>
    </mcdyn:DeviceConfigure>
    <mcdyn:LanguageAndCountry>
        <dd:ColdResetLanguageNoReboot></dd:ColdResetLanguageNoReboot>
        <mcdyn:CountryAndRegionNameNoReboot></mcdyn:CountryAndRegionNameNoReboot>
        <mcdyn:GenericPrompt></mcdyn:GenericPrompt>
    </mcdyn:LanguageAndCountry>
      <mcdyn:DeviceSetupWizards>
          <mcdyn:CustomerEnvironment>
               <mcdyn:SetupPrompt></mcdyn:SetupPrompt> 
          </mcdyn:CustomerEnvironment>
      </mcdyn:DeviceSetupWizards>
      <mcdyn:PrintEngineTestAbortCalibration></mcdyn:PrintEngineTestAbortCalibration>
      <mcdyn:MarkerDensityCalibration></mcdyn:MarkerDensityCalibration>
      <mcdyn:Counters>
          <dd:MonochromeImpressions></dd:MonochromeImpressions>
          <dd:ColorImpressions></dd:ColorImpressions>
      </mcdyn:Counters>
      <mcdyn:PrinterGeneralReset></mcdyn:PrinterGeneralReset>
      <mcdyn:PrintInputStatus>
          <dd:InputBin></dd:InputBin>
          <mcdyn:InputStatus></mcdyn:InputStatus>
      </mcdyn:PrintInputStatus>
      <mcdyn:ShipCartridgeInstalledInPrinter></mcdyn:ShipCartridgeInstalledInPrinter>
      <mcdyn:PaperConfig>
          <mcdyn:ColdResetPaperSize></mcdyn:ColdResetPaperSize>
      </mcdyn:PaperConfig>
      <mcdyn:SuppliesMfg>
        <mcdyn:AvgPageYield>
            <mcdyn:Starter>
                <mcdyn:BlackCartridge></mcdyn:BlackCartridge>
                <mcdyn:CyanCartridge></mcdyn:CyanCartridge>
                <mcdyn:MagentaCartridge></mcdyn:MagentaCartridge>
                <mcdyn:YellowCartridge></mcdyn:YellowCartridge>
            </mcdyn:Starter>
            <mcdyn:Normal>
                <mcdyn:BlackCartridge></mcdyn:BlackCartridge>
                <mcdyn:CyanCartridge></mcdyn:CyanCartridge>
                <mcdyn:MagentaCartridge></mcdyn:MagentaCartridge>
                <mcdyn:YellowCartridge></mcdyn:YellowCartridge>
            </mcdyn:Normal>
            <mcdyn:Other>
                <mcdyn:BlackCartridge></mcdyn:BlackCartridge>
                <mcdyn:CyanCartridge></mcdyn:CyanCartridge>
                <mcdyn:MagentaCartridge></mcdyn:MagentaCartridge>
                <mcdyn:YellowCartridge></mcdyn:YellowCartridge>
            </mcdyn:Other>
        </mcdyn:AvgPageYield>
        <mcdyn:AvgPagePixelCount>
            <mcdyn:BlackCartridge></mcdyn:BlackCartridge>
            <mcdyn:CyanCartridge></mcdyn:CyanCartridge>
            <mcdyn:MagentaCartridge></mcdyn:MagentaCartridge>
            <mcdyn:YellowCartridge></mcdyn:YellowCartridge>
        </mcdyn:AvgPagePixelCount>
        <mcdyn:RegionalCartridgeData>
            <mcdyn:RegionalCartridge>
                <dd:MarkerColor></dd:MarkerColor>
                <mcdyn:RegionCodeCounter></mcdyn:RegionCodeCounter>
                <mcdyn:RegionCodeUnsuccessfulCounter></mcdyn:RegionCodeUnsuccessfulCounter>
                <mcdyn:RegionCode></mcdyn:RegionCode>
            </mcdyn:RegionalCartridge>
         </mcdyn:RegionalCartridgeData>
      </mcdyn:SuppliesMfg>
      <mcdyn:EngineMargins>
        <mcdyn:TrayMarginAdjustmentVersion></mcdyn:TrayMarginAdjustmentVersion>
        <mcdyn:Tray1Margins>
            <mcdyn:X1Margin></mcdyn:X1Margin>
            <mcdyn:X2Margin></mcdyn:X2Margin>
            <mcdyn:Y1Margin></mcdyn:Y1Margin>
        </mcdyn:Tray1Margins>
        <mcdyn:Tray2Margins>
            <mcdyn:X1Margin></mcdyn:X1Margin>
            <mcdyn:X2Margin></mcdyn:X2Margin>
            <mcdyn:Y1Margin></mcdyn:Y1Margin>
        </mcdyn:Tray2Margins>
        <mcdyn:Tray3Margins>
            <mcdyn:X1Margin></mcdyn:X1Margin>
            <mcdyn:X2Margin></mcdyn:X2Margin>
            <mcdyn:Y1Margin></mcdyn:Y1Margin>
        </mcdyn:Tray3Margins>
      </mcdyn:EngineMargins>
  </mcdyn:ManufacturingConfigDyn>
"""

NET_APPS_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<nadyn:NetAppsDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:dd3="http://www.hp.com/schemas/imaging/con/dictionaries/2009/04/06" xmlns:nadyn="http://www.hp.com/schemas/imaging/con/ledm/netappdyn/2009/06/24" xmlns:nacap="http://www.hp.com/schemas/imaging/con/ledm/netappcap/2009/06/24" xmlns:ledm="http://www.hp.com/schemas/imaging/con/ledm/2007/09/21" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/dictionaries/2009/04/06 dd3/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/netappdyn/2009/06/24 NetAppsDyn.xsd http://www.hp.com/schemas/imaging/con/ledm/netappcap/2009/06/24 NetAppsCap.xsd http://www.hp.com/schemas/imaging/con/ledm/2007/09/21 LEDM.xsd">
  <nadyn:DNSSDConfig>
    <dd:MDNSSupport/>
    <dd:ApplicationServiceName/>
    <dd3:DomainName/>
    <dd:DNSSDPrintPreferredService/>
  </nadyn:DNSSDConfig>
  <nadyn:ProxyConfig>
    <dd:ResourceURI/>
    <dd:Port/>
    <dd:UserName/>
    <dd:ProxySupport/>
  </nadyn:ProxyConfig>
  <dd:SNMPConfigWithVersion>
    <dd:AccessOption/>
    <dd:GetCommunityNameConfig/>
    <dd:GetCommunityName/>
    <dd:SetCommunityName/>
    <dd:SNMP/>
    <dd:Version>
      <dd:Revision/>
    </dd:Version>
  </dd:SNMPConfigWithVersion>
  <nadyn:WebServicesConfig>
    <dd:WSDiscovery/>
  </nadyn:WebServicesConfig>
  <dd:AutoIP/>
  <dd:BOOTP/>
  <dd:DHCPv4/>
  <dd:DHCPv6/>
  <dd:LPD/>
  <dd:LLMNR/>
  <dd:SLPSupport/>
  <dd:HTTPSRedirection/>
  <nadyn:DirectPrint/>
  <nadyn:DirectPrintMode/>
</nadyn:NetAppsDyn>
"""

NET_APPS_SECURE_DYN = """<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<nasdyn:NetAppsSecureDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:dd3="http://www.hp.com/schemas/imaging/con/dictionaries/2009/04/06" xmlns:nasdyn="http://www.hp.com/schemas/imaging/con/ledm/netappsecdyn/2012/11/15" xmlns:nascap="http://www.hp.com/schemas/imaging/con/ledm/netappseccap/2012/11/15" xmlns:ledm="http://www.hp.com/schemas/imaging/con/ledm/2007/09/21" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/dictionaries/2009/04/06 dd3/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/2007/09/21 LEDM.xsd">
  <nasdyn:Version>
    <dd:Revision/>
    <dd:Date/>
  </nasdyn:Version>
  <nasdyn:NFCConfig>
    <nasdyn:State/>
  </nasdyn:NFCConfig>
  <nasdyn:WirelessDirectConfig>
    <nasdyn:ShowPassPhrase/>
  </nasdyn:WirelessDirectConfig>
</nasdyn:NetAppsSecureDyn>
"""

PRODUCT_CONFIG_DYN = """<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<prdcfgdyn2:ProductConfigDyn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:prdcfgdyn="http://www.hp.com/schemas/imaging/con/ledm/productconfigdyn/2007/11/05" xmlns:prdcfgdyn2="http://www.hp.com/schemas/imaging/con/ledm/productconfigdyn/2009/03/16" xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ dd/DataDictionaryMasterLEDM.xsd http://www.hp.com/schemas/imaging/con/ledm/productconfigdyn/2007/11/05 ProductConfigDyn.xsd http://www.hp.com/schemas/imaging/con/ledm/productconfigdyn/2009/03/16 ledm2/ProductConfigDyn.xsd">
  <dd:Version>
    <dd:Revision></dd:Revision>
  </dd:Version>
  <prdcfgdyn:ProductInformation>
    <dd:BoardInfo>
      <dd:BoardTypeEnum></dd:BoardTypeEnum>
      <dd:ModelNumber></dd:ModelNumber>
    </dd:BoardInfo>
    <dd:BoardInfo>
      <dd:BoardTypeEnum></dd:BoardTypeEnum>
      <dd:ModelNumber></dd:ModelNumber>
    </dd:BoardInfo>
    <dd:Version>
      <dd:Date></dd:Date>
    </dd:Version>
    <dd:MakeAndModel></dd:MakeAndModel>
    <dd:MakeAndModelBase></dd:MakeAndModelBase>
    <dd:MakeAndModelFirmwareDownload></dd:MakeAndModelFirmwareDownload>
    <dd:UUID></dd:UUID>
    <dd:SerialNumber></dd:SerialNumber>
    <dd:ProductNumber></dd:ProductNumber>
    <dd:ServiceID></dd:ServiceID>
    <dd:AvailableLanguages>
      <dd:Language></dd:Language>
      <dd:Language></dd:Language>
      <dd:Language></dd:Language>
      <dd:Language></dd:Language>
      <dd:Language></dd:Language>
    </dd:AvailableLanguages>
  </prdcfgdyn:ProductInformation>
  <prdcfgdyn2:ProductSettings>
  <dd:AssetNumber /> 
  <dd:CompanyName /> 
  <dd:CompanyContact /> 
  <dd:FriendlyName /> 
  <dd:PowerOnCalibration /> 
  <dd:EngineCalibrationTimer /> 
  <dd:PowerSaveTimeout />
  <dd:AutoOffTime />
  <dd:AutoOffAutoOn>
  <dd:AutoOffDelay>
  <dd:AutoOffDelaySetting />
  <dd:AutoOffDelayTime />
  <dd:AutoOnEvents>
  <dd:AutoOnEvent /> 
  </dd:AutoOnEvents>
  </dd:AutoOffDelay>
  <dd:AutoOffAutoOnPowerMeter />
  </dd:AutoOffAutoOn>
  <prdcfgdyn:ProductLanguage>
  <dd:DeviceLanguage /> 
  <dd:PreferredLanguage /> 
  <dd:ColdResetLanguage /> 
  </prdcfgdyn:ProductLanguage>
  <prdcfgdyn:CountryAndRegionName /> 
  <dd:ManualFeed /> 
  <dd:GenericCountryPrompt /> 
  <dd:GenericLanguagePrompt /> 
  <dd:ShowIPAddress />
  <prdcfgdyn:DeviceInformation>
  <dd:DeviceLocation /> 
  </prdcfgdyn:DeviceInformation>
  <dd:SmartInstall /> 
  </prdcfgdyn2:ProductSettings>
  <prdcfgdyn:Memory>
    <dd:AvailableMemory />
    <dd:TotalMemory />
  </prdcfgdyn:Memory>
  <prdcfgdyn:EmailAlerts>
    <prdcfgdyn:Address>
      <dd:EmailAddress />
    </prdcfgdyn:Address>
    <prdcfgdyn:Address>
      <dd:EmailAddress />
    </prdcfgdyn:Address>
  </prdcfgdyn:EmailAlerts>
</prdcfgdyn2:ProductConfigDyn>
"""

WIFI_PROFILE = """<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp1 (http://www.altova.com)-->
<io:Profile
xmlns:io="http://www.hp.com/schemas/imaging/con/ledm/iomgmt/2008/11/30" 
xmlns:wifi="http://www.hp.com/schemas/imaging/con/wifi/2009/06/26" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/ledm/iomgmt/2008/11/30 ../../schemas/IoMgmt.xsd" >
	<io:AdapterProfile>
		<io:WifiProfile>
				<wifi:Locale></wifi:Locale>
		</io:WifiProfile>
	</io:AdapterProfile>
</io:Profile>
"""